services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto del Broker
      - "15672:15672" # Puerto de la UI de manejo
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - distributed_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 10s
      retries: 5

  entrypoint:
    image: entrypoint:latest
    container_name: entrypoint
    entrypoint: /entrypoint
    networks:
      - distributed_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  game_mapper:
    image: game_mapper:latest
    container_name: game_mapper
    entrypoint: /mappers/game_mapper
    networks:
      - distributed_network
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  os_accumulator:
    image: os_accumulator:latest
    container_name: os_accumulator
    entrypoint: /accumulators/os_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  os_accumulator_2:
    image: os_accumulator:latest
    container_name: os_accumulator_2
    entrypoint: /accumulators/os_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  os_final_accumulator:
    image: os_final_accumulator:latest
    container_name: os_final_accumulator
    entrypoint: /accumulators/os_final_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  top_ten_accumulator:
    image: top_ten_accumulator:latest
    container_name: top_ten_accumulator
    entrypoint: /accumulators/top_ten_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  review_mapper:
    image: review_mapper:latest
    container_name: review_mapper
    entrypoint: /mappers/review_mapper
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  decade_filter:
    image: decade_filter:latest
    container_name: decade_filter
    entrypoint: /filters/decade_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  english_filter:
    image: english_filter:latest
    container_name: english_filter
    entrypoint: /filters/english_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started

  review_accumulator:
    image: review_accumulator:latest
    container_name: review_accumulator
    entrypoint: /accumulators/review_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  positive_reviews_filter:
    image: positive_reviews_filter:latest
    container_name: positive_reviews_filter
    entrypoint: /filters/positive_reviews_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  action_review_joiner:
    image: action_review_joiner:latest
    container_name: action_review_joiner
    entrypoint: /joiners/action_review_joiner
    networks:
      - distributed_network
    depends_on:
      review_mapper:
        condition: service_started
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  writer:
    image: writer:latest
    container_name: writer
    entrypoint: /writer
    networks:
      - distributed_network
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy

networks:
  distributed_network:
    name: distributed_network
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/24
