services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - distributed_network

  entrypoint:
    container_name: entrypoint
    image: entrypoint:latest
    entrypoint: /entrypoint
    environment:
      - ACTION_REVIEW_JOINERS_AMOUNT=5
      - REVIEW_ACCUMULATORS_AMOUNT=4
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  game_mapper:
    container_name: game_mapper
    image: game_mapper:latest
    entrypoint: /game_mapper
    environment:
      - OS_ACCUMULATORS_AMOUNT=2
      - DECADE_FILTER_AMOUNT=2
      - INDIE_REVIEW_JOINERS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  os_accumulator_1:
    container_name: os_accumulator_1
    image: os_accumulator:latest
    entrypoint: /os_accumulator
    environment:
      - ID=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  os_accumulator_2:
    container_name: os_accumulator_2
    image: os_accumulator:latest
    entrypoint: /os_accumulator
    environment:
      - ID=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  os_final_accumulator:
    container_name: os_final_accumulator
    image: os_final_accumulator:latest
    entrypoint: /os_final_accumulator
    environment:
      - NUM_PREVIOUS_OS_ACCUMULATORS=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  top_ten_accumulator:
    container_name: top_ten_accumulator
    image: top_ten_accumulator:latest
    entrypoint: /top_ten_accumulator
    environment:
      - DECADE_FILTERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  top_positive_reviews:
    container_name: top_positive_reviews
    image: top_positive_reviews:latest
    entrypoint: /top_positive_reviews
    environment:
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  percentile_accumulator:
    container_name: percentile_accumulator
    image: percentile_accumulator:latest
    entrypoint: /percentile_accumulator
    environment:
      - NUM_PREVIOUS_ACCUMULATORS=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  reviews_accumulator_1:
    container_name: reviews_accumulator_1
    image: reviews_accumulator:latest
    entrypoint: /reviews_accumulator
    environment:
      - ID=1
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  reviews_accumulator_2:
    container_name: reviews_accumulator_2
    image: reviews_accumulator:latest
    entrypoint: /reviews_accumulator
    environment:
      - ID=2
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  reviews_accumulator_3:
    container_name: reviews_accumulator_3
    image: reviews_accumulator:latest
    entrypoint: /reviews_accumulator
    environment:
      - ID=3
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  reviews_accumulator_4:
    container_name: reviews_accumulator_4
    image: reviews_accumulator:latest
    entrypoint: /reviews_accumulator
    environment:
      - ID=4
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  decade_filter_1:
    container_name: decade_filter_1
    image: decade_filter:latest
    entrypoint: /decade_filter
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  decade_filter_2:
    container_name: decade_filter_2
    image: decade_filter:latest
    entrypoint: /decade_filter
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_review_joiner_1:
    container_name: action_review_joiner_1
    image: action_review_joiner:latest
    entrypoint: /action_review_joiner
    environment:
      - ID=1
      - ENGLISH_FILTERS_AMOUNT=5
      - ACTION_REVIEWS_ACCUMULATORS_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_review_joiner_2:
    container_name: action_review_joiner_2
    image: action_review_joiner:latest
    entrypoint: /action_review_joiner
    environment:
      - ID=2
      - ENGLISH_FILTERS_AMOUNT=5
      - ACTION_REVIEWS_ACCUMULATORS_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_review_joiner_3:
    container_name: action_review_joiner_3
    image: action_review_joiner:latest
    entrypoint: /action_review_joiner
    environment:
      - ID=3
      - ENGLISH_FILTERS_AMOUNT=5
      - ACTION_REVIEWS_ACCUMULATORS_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_review_joiner_4:
    container_name: action_review_joiner_4
    image: action_review_joiner:latest
    entrypoint: /action_review_joiner
    environment:
      - ID=4
      - ENGLISH_FILTERS_AMOUNT=5
      - ACTION_REVIEWS_ACCUMULATORS_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_review_joiner_5:
    container_name: action_review_joiner_5
    image: action_review_joiner:latest
    entrypoint: /action_review_joiner
    environment:
      - ID=5
      - ENGLISH_FILTERS_AMOUNT=5
      - ACTION_REVIEWS_ACCUMULATORS_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_filter_1:
    container_name: english_filter_1
    image: english_reviews_filter:latest
    entrypoint: /english_reviews_filter
    environment:
      - ID=1
      - ACCUMULATORS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_filter_2:
    container_name: english_filter_2
    image: english_reviews_filter:latest
    entrypoint: /english_reviews_filter
    environment:
      - ID=2
      - ACCUMULATORS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_filter_3:
    container_name: english_filter_3
    image: english_reviews_filter:latest
    entrypoint: /english_reviews_filter
    environment:
      - ID=3
      - ACCUMULATORS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_filter_4:
    container_name: english_filter_4
    image: english_reviews_filter:latest
    entrypoint: /english_reviews_filter
    environment:
      - ID=4
      - ACCUMULATORS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_filter_5:
    container_name: english_filter_5
    image: english_reviews_filter:latest
    entrypoint: /english_reviews_filter
    environment:
      - ID=5
      - ACCUMULATORS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_reviews_accumulator_1:
    container_name: english_reviews_accumulator_1
    image: english_reviews_accumulator:latest
    entrypoint: /english_reviews_accumulator
    environment:
      - ID=1
      - FILTERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_reviews_accumulator_2:
    container_name: english_reviews_accumulator_2
    image: english_reviews_accumulator:latest
    entrypoint: /english_reviews_accumulator
    environment:
      - ID=2
      - FILTERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  negative_reviews_filter:
    container_name: negative_reviews_filter
    image: negative_reviews_filter:latest
    entrypoint: /negative_reviews_filter
    environment:
      - ENGLISH_REVIEW_ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_reviews_accumulator_1:
    container_name: action_reviews_accumulator_1
    image: action_reviews_accumulator:latest
    entrypoint: /action_reviews_accumulator
    environment:
      - ID=1
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_reviews_accumulator_2:
    container_name: action_reviews_accumulator_2
    image: action_reviews_accumulator:latest
    entrypoint: /action_reviews_accumulator
    environment:
      - ID=2
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_reviews_accumulator_3:
    container_name: action_reviews_accumulator_3
    image: action_reviews_accumulator:latest
    entrypoint: /action_reviews_accumulator
    environment:
      - ID=3
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_reviews_accumulator_4:
    container_name: action_reviews_accumulator_4
    image: action_reviews_accumulator:latest
    entrypoint: /action_reviews_accumulator
    environment:
      - ID=4
      - ACTION_REVIEW_JOINERS_AMOUNT=5
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  indie_review_joiner_1:
    container_name: indie_review_joiner_1
    image: indie_review_joiner:latest
    entrypoint: /indie_review_joiner
    environment:
      - ID=1
      - REVIEWS_ACCUMULATOR_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  indie_review_joiner_2:
    container_name: indie_review_joiner_2
    image: indie_review_joiner:latest
    entrypoint: /indie_review_joiner
    environment:
      - ID=2
      - REVIEWS_ACCUMULATOR_AMOUNT=4
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  watchdog3:
    container_name: watchdog3
    image: watchdog:latest
    entrypoint: /watchdog
    environment:
      - WATCHDOG_HOST=3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      english_filter_1:
        condition: service_started
      english_reviews_accumulator_2:
        condition: service_started
      os_accumulator_1:
        condition: service_started
      top_positive_reviews:
        condition: service_started
      percentile_accumulator:
        condition: service_started
      reviews_accumulator_4:
        condition: service_started
      top_ten_accumulator:
        condition: service_started
      english_reviews_accumulator_1:
        condition: service_started
      action_reviews_accumulator_2:
        condition: service_started
      indie_review_joiner_1:
        condition: service_started
      action_reviews_accumulator_1:
        condition: service_started
      os_final_accumulator:
        condition: service_started
      reviews_accumulator_3:
        condition: service_started
      action_review_joiner_1:
        condition: service_started
      action_review_joiner_4:
        condition: service_started
      action_reviews_accumulator_3:
        condition: service_started
      game_mapper:
        condition: service_started
      decade_filter_2:
        condition: service_started
      action_review_joiner_5:
        condition: service_started
      english_filter_5:
        condition: service_started
      action_reviews_accumulator_4:
        condition: service_started
      indie_review_joiner_2:
        condition: service_started
      decade_filter_1:
        condition: service_started
      action_review_joiner_2:
        condition: service_started
      english_filter_2:
        condition: service_started
      english_filter_3:
        condition: service_started
      reviews_accumulator_2:
        condition: service_started
      action_review_joiner_3:
        condition: service_started
      english_filter_4:
        condition: service_started
      negative_reviews_filter:
        condition: service_started
      rabbitmq:
        condition: service_started
      entrypoint:
        condition: service_started
      os_accumulator_2:
        condition: service_started
      reviews_accumulator_1:
        condition: service_started
    networks:
      - distributed_network

  watchdog1:
    container_name: watchdog1
    image: watchdog:latest
    entrypoint: /watchdog
    environment:
      - WATCHDOG_HOST=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      watchdog3:
        condition: service_started
    networks:
      - distributed_network

  watchdog2:
    container_name: watchdog2
    image: watchdog:latest
    entrypoint: /watchdog
    environment:
      - WATCHDOG_HOST=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      watchdog3:
        condition: service_started
    networks:
      - distributed_network

networks:
  distributed_network:
    name: distributed_network
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/24
