services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto del Broker
      - "15672:15672" # Puerto de la UI de manejo
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - distributed_network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 15s
      timeout: 10s
      retries: 5

  entrypoint:
    image: entrypoint:latest
    container_name: entrypoint
    entrypoint: /entrypoint
    networks:
      - distributed_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  examplenode:
    image: examplenode:latest
    container_name: examplenode
    entrypoint: /examplenode
    networks:
      - distributed_network
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy

networks:
  distributed_network:
    name: distributed_network
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/24
