services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto del Broker
      - "15672:15672" # Puerto de la UI de manejo
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - distributed_network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 15s
      timeout: 10s
      retries: 5

  entrypoint:
    image: entrypoint:latest
    container_name: entrypoint
    entrypoint: /entrypoint
    networks:
      - distributed_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  game_mapper:
    image: game_mapper:latest
    container_name: game_mapper
    entrypoint: /mappers/game_mapper
    networks:
      - distributed_network
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  os_accumulator:
    image: os_accumulator:latest
    container_name: os_accumulator
    entrypoint: /accumulators/os_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  os_accumulator_2:
    image: os_accumulator:latest
    container_name: os_accumulator_2
    entrypoint: /accumulators/os_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  os_final_accumulator:
    image: os_final_accumulator:latest
    container_name: os_final_accumulator
    entrypoint: /accumulators/os_final_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  top_ten_accumulator:
    image: top_ten_accumulator:latest
    container_name: top_ten_accumulator
    entrypoint: /accumulators/top_ten_accumulator
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  top_positive_reviews:
    image: top_positive_reviews:latest
    container_name: top_positive_reviews
    entrypoint: /filters/top_positive_reviews
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  review_mapper_1:
    image: review_mapper:latest
    container_name: review_mapper_1
    entrypoint: /mappers/review_mapper
    networks:
      - distributed_network
    environment:
      - ID=1
      - ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  review_mapper_2:
    image: review_mapper:latest
    container_name: review_mapper_2
    entrypoint: /mappers/review_mapper
    networks:
      - distributed_network
    environment:
      - ID=2
      - ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  reviews_accumulator_1:
    image: reviews_accumulator:latest
    container_name: reviews_accumulator_1
    entrypoint: /accumulators/reviews_accumulator
    networks:
      - distributed_network
    environment:
      - ID=1
      - MAPPERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  reviews_accumulator_2:
    image: reviews_accumulator:latest
    container_name: reviews_accumulator_2
    entrypoint: /accumulators/reviews_accumulator
    networks:
      - distributed_network
    environment:
      - ID=2
      - MAPPERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  decade_filter:
    image: decade_filter:latest
    container_name: decade_filter
    entrypoint: /filters/decade_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  decade_filter2:
    image: decade_filter:latest
    container_name: decade_filter2
    entrypoint: /filters/decade_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  decade_filter3:
    image: decade_filter:latest
    container_name: decade_filter3
    entrypoint: /filters/decade_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  english_filter_1:
    image: english_filter:latest
    container_name: english_filter_1
    entrypoint: /filters/english_filter
    networks:
      - distributed_network
    environment:
      - ID=1
      - ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started

  english_filter_2:
    image: english_filter:latest
    container_name: english_filter_2
    entrypoint: /filters/english_filter
    networks:
      - distributed_network
    environment:
      - ID=2
      - ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started

  english_reviews_accumulator_1:
    image: english_reviews_accumulator:latest
    container_name: english_reviews_accumulator_1
    entrypoint: /accumulators/english_reviews_accumulator
    networks:
      - distributed_network
    environment:
      - ID=1
      - FILTERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  english_reviews_accumulator_2:
    image: english_reviews_accumulator:latest
    container_name: english_reviews_accumulator_2
    entrypoint: /accumulators/english_reviews_accumulator
    networks:
      - distributed_network
    environment:
      - ID=2
      - FILTERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  positive_reviews_filter:
    image: positive_reviews_filter:latest
    container_name: positive_reviews_filter
    entrypoint: /filters/positive_reviews_filter
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  action_review_joiner:
    image: action_review_joiner:latest
    container_name: action_review_joiner
    entrypoint: /joiners/action_review_joiner
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  indie_review_joiner:
    image: indie_review_joiner:latest
    container_name: indie_review_joiner
    entrypoint: /joiners/indie_review_joiner
    networks:
      - distributed_network
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  writer:
    image: writer:latest
    container_name: writer
    entrypoint: /writer
    networks:
      - distributed_network
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy

networks:
  distributed_network:
    name: distributed_network
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/24
