services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - distributed_network

  entrypoint:
    container_name: entrypoint
    image: entrypoint:latest
    entrypoint: /entrypoint
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  game_mapper:
    container_name: game_mapper
    image: game_mapper:latest
    entrypoint: /mappers/game_mapper
    environment:
      - OS_ACCUMULATORS_AMOUNT=2
      - DECADE_FILTER_AMOUNT=2
      - INDIE_REVIEW_JOINERS_AMOUNT=2
      - ACTION_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  os_accumulator_1:
    container_name: os_accumulator_1
    image: os_accumulator:latest
    entrypoint: /accumulators/os_accumulator
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  os_accumulator_2:
    container_name: os_accumulator_2
    image: os_accumulator:latest
    entrypoint: /accumulators/os_accumulator
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  os_final_accumulator:
    container_name: os_final_accumulator
    image: os_final_accumulator:latest
    entrypoint: /accumulators/os_final_accumulator
    environment:
      - NUM_PREVIOUS_OS_ACCUMULATORS=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  top_ten_accumulator:
    container_name: top_ten_accumulator
    image: top_ten_accumulator:latest
    entrypoint: /accumulators/top_ten_accumulator
    environment:
      - DECADE_FILTERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  top_positive_reviews:
    container_name: top_positive_reviews
    image: top_positive_reviews:latest
    entrypoint: /filters/top_positive_reviews
    environment:
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  percentile_accumulator:
    container_name: percentile_accumulator
    image: percentile_accumulator:latest
    entrypoint: /accumulators/percentile_accumulator
    environment:
      - ACTION_NEGATIVE_REVIEWS_JOINERS_AMOUNT=2
      - NUM_PREVIOUS_ACCUMULATORS=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  review_mapper_1:
    container_name: review_mapper_1
    image: review_mapper:latest
    entrypoint: /mappers/review_mapper
    environment:
      - ID=1
      - ACCUMULATORS_AMOUNT=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  review_mapper_2:
    container_name: review_mapper_2
    image: review_mapper:latest
    entrypoint: /mappers/review_mapper
    environment:
      - ID=2
      - ACCUMULATORS_AMOUNT=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  reviews_accumulator_1:
    container_name: reviews_accumulator_1
    image: reviews_accumulator:latest
    entrypoint: /accumulators/reviews_accumulator
    environment:
      - ID=1
      - MAPPERS_AMOUNT=2
      - INDIE_REVIEW_JOINERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  decade_filter_1:
    container_name: decade_filter_1
    image: decade_filter:latest
    entrypoint: /filters/decade_filter
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  decade_filter_2:
    container_name: decade_filter_2
    image: decade_filter:latest
    entrypoint: /filters/decade_filter
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_filter_1:
    container_name: english_filter_1
    image: english_filter:latest
    entrypoint: /filters/english_filter
    environment:
      - ID=1
      - ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_reviews_accumulator_1:
    container_name: english_reviews_accumulator_1
    image: english_reviews_accumulator:latest
    entrypoint: /accumulators/english_reviews_accumulator
    environment:
      - ID=1
      - FILTERS_AMOUNT=1
      - POSITIVE_REVIEWS_FILTER_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  english_reviews_accumulator_2:
    container_name: english_reviews_accumulator_2
    image: english_reviews_accumulator:latest
    entrypoint: /accumulators/english_reviews_accumulator
    environment:
      - ID=2
      - FILTERS_AMOUNT=1
      - POSITIVE_REVIEWS_FILTER_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  positive_reviews_filter_1:
    container_name: positive_reviews_filter_1
    image: positive_reviews_filter:latest
    entrypoint: /filters/positive_reviews_filter
    environment:
      - ACTION_POSITIVE_REVIEWS_JOINERS_AMOUNT=2
      - ENGLISH_REVIEW_ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  positive_reviews_filter_2:
    container_name: positive_reviews_filter_2
    image: positive_reviews_filter:latest
    entrypoint: /filters/positive_reviews_filter
    environment:
      - ACTION_POSITIVE_REVIEWS_JOINERS_AMOUNT=2
      - ENGLISH_REVIEW_ACCUMULATORS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_positive_review_joiner_1:
    container_name: action_positive_review_joiner_1
    image: action_positive_review_joiner:new_version
    entrypoint: /action_positive_review_joiner
    environment:
      - ID=1
      - POSITIVE_REVIEWS_FILTERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_positive_review_joiner_2:
    container_name: action_positive_review_joiner_2
    image: action_positive_review_joiner:new_version
    entrypoint: /action_positive_review_joiner
    environment:
      - ID=2
      - POSITIVE_REVIEWS_FILTERS_AMOUNT=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_negative_review_joiner_1:
    container_name: action_negative_review_joiner_1
    image: action_negative_review_joiner:latest
    entrypoint: /joiners/action_negative_review_joiner
    environment:
      - ID=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  action_negative_review_joiner_2:
    container_name: action_negative_review_joiner_2
    image: action_negative_review_joiner:latest
    entrypoint: /joiners/action_negative_review_joiner
    environment:
      - ID=2
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  indie_review_joiner_1:
    container_name: indie_review_joiner_1
    image: indie_review_joiner:latest
    entrypoint: /joiners/indie_review_joiner
    environment:
      - ID=1
      - REVIEWS_ACCUMULATOR_AMOUNT=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  indie_review_joiner_2:
    container_name: indie_review_joiner_2
    image: indie_review_joiner:latest
    entrypoint: /joiners/indie_review_joiner
    environment:
      - ID=2
      - REVIEWS_ACCUMULATOR_AMOUNT=1
    depends_on:
      game_mapper:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

  writer:
    container_name: writer
    image: writer:latest
    entrypoint: /writer
    environment:
      - ACTION_NEGATIVE_REVIEWS_JOINERS_AMOUNT=2
      - ACTION_POSITIVE_REVIEWS_JOINERS_AMOUNT=2
    depends_on:
      entrypoint:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - distributed_network

networks:
  distributed_network:
    name: distributed_network
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/24
